# Understanding Geometry {#sec-understanding-geometry}

Let's face it, the world is three-dimensional (3D), and vision systems capture only two-dimensional (2D) images. Understanding the projection of the 3D world into 2D images, and how to reverse this projection to recover the 3D structure of the scene, is one of the most important topics in the study of vision (both natural vision and computer vision). Geometry is therefore a fundamental tool in computer vision. 

This collection of chapters will cover many aspects of 3D vision:

## Outline

- **Chapter @sec-geometry_homogeneous** introduces homogeneous and heterogeneous coordinate systems and how to use them to model geometric transformations.

- **Chapter @sec-camera_parameters** describes camera models (intrinsic and extrinsic camera parameters) and camera calibration.

- **Chapter @sec-stereo_vision** describes how to recover 3D information from stereo images.

- **Chapter @sec-homography** describes homographies and their application to build image panoramas.

- **Chapter @sec-3D_single_view** describes how to recover 3D information using only a single image.

The material in this set of chapters will come in handy as soon as you have to deal with 3D scenes (i.e., always).