# Foundations {#sec-foundations}

This first block of three chapters defines the problem that computer vision tries to solve, introduces some of the mathematical tools one needs to be familiar with, and poses the study of computer vision as a scientific and engineering effort with an enormous societal impact that the reader should be familiar with initially and not as an afterthought.

## Outline

- **Chapter {@sec-simplesystem}** will make you think about the math foundations needed to understand the rest of the book and it will also introduce some important general concepts in vision.

- **Chapter {@sec-looking-at-images}** will make you think about the vision problem from the perspective of an observer.

- **Chapter {@sec-computer-vision-and-society}** will make you think about the social implications of this area of work.

Readers might want to skip this part and directly jump into the latest and most exciting techniques in computer vision (deep learning, image generative models) that will be presented later in the book, but it is important to slow down and be patient. We believe that being patient will result in rewards in the long run. Let's first focus on foundational concepts.